[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "VueQueue"
authors = [{name = "Elias", email = "liasides.elias@gmail.com"}]
dynamic = ["version", "description"]
